### ISSUE TITLE
Language ID/name mismatch

### ISSUE THREAD

**Issue by xrotwang** [cldf-datasets/normansinitic#4]
The two files with raw data do **not** have matching languages:
```
(cldf) $ csvcut -c DOCULECT,DOCULECT_IN_SOURCE -t raw/words.tsv | sort | uniq
Beijing,Bj
Common_Chinese,CC
DOCULECT,DOCULECT_IN_SOURCE
Guangzhou,Gz
Heping,Hp
Jianchuan,Jc
Jiangshan,Js
Jiangyong,Jy
Meixian,Mx
Nanchang,Nc
Suzhou,Sz
Zhenqian,Zq
(cldf) $ csvcut -c DOCULECT,DOCULECT_IN_SOURCE -t raw/structures.tsv | sort | uniq
Beijing,Bj
Changsha,Cs
DOCULECT,DOCULECT_IN_SOURCE
Guangzhou,Gz
Jiangyong,Jy
Meixian,Mx
Nanchang,Nc
Shuangfeng,Sf
Suzhou,Sz
Taiyuan,Ty
Wenzhou,Wz
Yangzhou,Yz
```

**Comment by xrotwang** [comment]
The two sets should be consolidated and the consolidated list should be used to correct `etc/languages.csv`.

**Comment by LinguList** [comment]
it's easier. 

modify this line:

```python
            for vals in self.raw_dir.read_csv('structures.tsv', delimiter='\t', dicts=True):
                vidx, lidx, pidx = vals['ID'], vals['DOCULECT_IN_SOURCE'], vals['STRUCTURE_ID']
                idx = '{0}-{1}-{2}'.format(lidx, pidx, vidx)
```

to this line

```python
            for vals in self.raw_dir.read_csv('structures.tsv', delimiter='\t', dicts=True):
                vidx, lidx, pidx = vals['ID'], vals['DOCULECT'], vals['STRUCTURE_ID']
                idx = '{0}-{1}-{2}'.format(lidx, pidx, vidx)
```

I'll push it soon.

**Comment by xrotwang** [comment]
Nope. Neither `DOCULECT` nor `DOCULECT_IN_SOURCE` in the two raw files match. Just run
```
cldf validate cldf/StructureDataset-metadata.json
```

**Comment by LinguList** [comment]
ah, sorry, let me look again.

**Comment by LinguList** [comment]
Okay, but Mx, etc. is NOT the ID, in the new version, the ID is Meixian.

**Comment by xrotwang** [comment]
Yes, but it doesn't work with names either.

**Comment by xrotwang** [comment]
```
...
WARNING cldf/values.csv:129 Key Shuangfeng not found in table languages.csv
WARNING cldf/values.csv:135 Key Taiyuan not found in table languages.csv
WARNING cldf/values.csv:136 Key Yangzhou not found in table languages.csv
WARNING cldf/values.csv:138 Key Wenzhou not found in table languages.csv
WARNING cldf/values.csv:139 Key Changsha not found in table languages.csv
WARNING cldf/values.csv:140 Key Shuangfeng not found in table languages.csv
WARNING cldf/values.csv:146 Key Taiyuan not found in table languages.csv
WARNING cldf/values.csv:147 Key Yangzhou not found in table languages.csv
WARNING cldf/values.csv:149 Key Wenzhou not found in table languages.csv
WARNING cldf/values.csv:150 Key Changsha not found in table languages.csv
WARNING cldf/values.csv:151 Key Shuangfeng not found in table languages.csv
WARNING cldf/values.csv:157 Key Taiyuan not found in table languages.csv
WARNING cldf/values.csv:158 Key Yangzhou not found in table languages.csv
WARNING cldf/values.csv:160 Key Wenzhou not found in table languages.csv
WARNING cldf/values.csv:161 Key Changsha not found in table languages.csv
WARNING cldf/values.csv:162 Key Shuangfeng not found in table languages.csv
```

**Comment by LinguList** [comment]
Ah, yes. this is the crap: the datasets are only PARTIALLY overlapping. Like, Common Chinese is not given in features, etc.

**Comment by LinguList** [comment]
So I have to add them to the languages.csv in etc.

**Comment by xrotwang** [comment]
Ok, but then we need to have the union of the language sets in `etc/languages.csv`.

**Comment by LinguList** [comment]
I'm disappointed now: I thought this was the perfect dataset, and then the author actually uses non-overlapping subsets in order to discuss dialect classification.

**Comment by xrotwang** [comment]
It's still sort of perfect - showing that in the absence of true, computational comparability all sorts of claims can be made.

**Comment by LinguList** [comment]
Yes. I am running in a problem now: I added the languages, but they do not seem to show up. So the lexibank writer seems to accept only those languages that occur in the data for the language table? Then do we need to add them manually?

**Comment by xrotwang** [comment]
Hm. let me check why that happens. We may need a flag then, preventing this behaviour.

**Comment by xrotwang** [comment]
See https://github.com/lexibank/pylexibank/issues/158
For now, we can just resort to re-creating the language table from the structure dataset writer.

**Comment by LinguList** [comment]
Okay! can you handle this? As I'm not that sure how I'd modify that table now best...

**Comment by xrotwang** [comment]
One is still missing:
```
WARNING cldf/values.csv:7 Key Changsha not found in table languages.csv
```

**Comment by xrotwang** [comment]
Practising our tools is actually quite useful - see also https://github.com/cldf/pycldf/issues/98 :)

**Comment by LinguList** [comment]
Yes, practice is the mother of all theory.

**Comment by LinguList** [comment]
I updated the language, but there's a but when I run the cldfbench. 

```python
Traceback (most recent call last):
  File "/home/mattis/.virtualenvs/lexi/bin/cldfbench", line 11, in <module>
    load_entry_point('cldfbench', 'console_scripts', 'cldfbench')()
  File "/home/mattis/.virtualenvs/lexi/lib/python3.7/site-packages/cldfbench-1.0.0-py3.7.egg/cldfbench/__main__.py", line 75, in main
    return args.main(args) or 0
  File "/home/mattis/.virtualenvs/lexi/lib/python3.7/site-packages/pylexibank-2.1.0-py3.7.egg/pylexibank/commands/makecldf.py", line 19, in run
    with_dataset(args, 'makecldf', dataset=dataset)
  File "/home/mattis/.virtualenvs/lexi/lib/python3.7/site-packages/cldfbench-1.0.0-py3.7.egg/cldfbench/cli_util.py", line 82, in with_dataset
    func(*arg, args)
  File "/home/mattis/.virtualenvs/lexi/lib/python3.7/site-packages/pylexibank-2.1.0-py3.7.egg/pylexibank/dataset.py", line 188, in _cmd_makecldf
    assert self.cldf_reader().validate(args.log)
AssertionError
```

Is this related to cldf/pycldf#98?

**Comment by xrotwang** [comment]
No, that's the ill-formatted coordinates introduced with your last commit. Running
```
cldf validate cldf/cldf-metadata.json
```
may give more informative output.

**Comment by LinguList** [comment]
I hate libre office. It is a pain editing tables in a text editor, but it is even as worse to have a spreadsheet that thinks it was intelligent. Sorry.

**Comment by LinguList** [comment]
Okay, I just fixed the numbers now.
